redmine_settings:
  # URL must have a final slash - like "http://127.0.0.1/"
  url: 'REDMINE_URL'
  api_key: API_KEY
deployment_groups:
  # Strings, not ints
  dev: '5'
  stage: '6'
  preprod: '7'
  prod: '8'
# 'json' or 'xml'
api_format: 'json'
