redmine_settings:
  # URL must have a final slash - like "http://127.0.0.1/"
  url: 'REDMINE_URL'
  api_key: API_KEY
deployment_groups:
  # Strings, not ints
  dev: DEV_ID
  stage: STAGE_ID
  preprod: PREPROD_ID
  prod: '8'
# 'json' or 'xml'
api_format: 'json'
