redmine_settings:
  # URL must have a final slash - like "http://127.0.0.1/"
  url: 'REDMINE_URL'
  api_key: API_KEY
deployment_groups:
  # Strings, not ints
  dev: DEV_ID
  stage: STAGE_ID
  preprod: PREPROD_ID
  prod: PROD_ID
# 'json' or 'xml'
api_format: 'json'
issue_params:
  project_id: PRJ_ID
  priority_id: PRIORITY_ID
  subject: "Deployment to {env}. {date}"
# todo: Add http auth handling.
http_auth:
  enabled: False
  username: USERNAME
  pass: PASSWORD
