redmine_settings:
  url: 'YOUR_HOST'
  api_key: YOUR_API_KEY
deployment_groups:
  dev: DEV_GROUP
  stage: STAGE_GROUP
  preprod: PREPROD_GROUP
  prod: PREPROD_GROUP
# 'json' or 'xml'
api_format: 'json'
